// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MediaInfo = {
  title: string | null;
  artist: string | null;
  album: string | null;
  status: string;
  position: number;
  length: number | null;
  can_play: boolean;
  can_pause: boolean;
  can_seek: boolean;
};
