// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SystemInfo = {
  cpu_used: number;
  disk_used: number;
  ram_used: number;
  net_both: number;
  net_in: number;
  net_out: number;
};
