// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceInfo = {
  id: number;
  name: string;
  monitor: string;
  windows: number;
  fullscreen: boolean;
  last_window: string | null;
  is_active: boolean;
};
